### ISSUE TITLE
Hamburger color is offset from the actual button in mobile

### ISSUE THREAD

**Issue by helloitsrufio** [helloitsrufio/Southern-Paiute-Talking-Dictionary#5]
# Description

When the user is on mobile and uses the hamburger drop-down menu, the darker blue color doesn't fully cover the hamburger icon + space to the right. 

![image](https://user-images.githubusercontent.com/75654453/194908927-bdd81304-c74f-46d3-9c5e-d0db157ca6eb.png)

**Comment by devlark** [comment]
Files related to the issue. 

https://github.com/helloitsrufio/Southern-Paiute-Talking-Dictionary/blob/d8a59e9fe2817a96f3d7ffd9d54c02f13ef86510/views/partials/navbar.ejs#L1 

https://github.com/helloitsrufio/Southern-Paiute-Talking-Dictionary/blob/d8a59e9fe2817a96f3d7ffd9d54c02f13ef86510/sass/partials/_nav.scss#L3

**Comment by devlark** [comment]
The problem is in these lines:

The margin-right is pushing the box right, duh.

## Possible solution:

remove:
https://github.com/helloitsrufio/Southern-Paiute-Talking-Dictionary/blob/d8a59e9fe2817a96f3d7ffd9d54c02f13ef86510/sass/partials/_nav.scss#L63
and replace with `padding: 1.85rem;`

----
here we can remove the padding:

https://github.com/helloitsrufio/Southern-Paiute-Talking-Dictionary/blob/d8a59e9fe2817a96f3d7ffd9d54c02f13ef86510/sass/partials/_nav.scss#L79
---

both combined should remove the offset and make it look like a normal healthy burger.
![2022-10-10 231822](https://user-images.githubusercontent.com/80993072/194982446-a4f60506-0872-4fb0-854c-39eefac3d4c5.jpg)

**Comment by devlark** [comment]
:shipit:
